name: Test & static analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.1"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "highest"

      - name: "Run our codestyle checker"
        run: "vendor/bin/phpcs"
  phpstan:
    runs-on: "ubuntu-20.04"
    
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.1"

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "highest"

    - name: "Run a static analysis with phpstan/phpstan"
      run: "vendor/bin/phpstan analyse"
      
  phpunit:
    runs-on: "ubuntu-20.04"
    
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.1"

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "highest"

    - name: Run test suite
      run: vendor/bin/phpunit
